version: '3'

volumes:
  volume-mongo:
  volume-mysql:

services:
  mongoserver:
    image: mongo
    volumes:
      - volume-mongo:/data/db

  mysqlserver:
    image: chesszebra/mysql:5.5
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - volume-mysql:/var/lib/mysql

  php:
    image: chesszebra/php:7.2-cli
    volumes:
      - .:/data
    links:
      - mongoserver
      - mysqlserver

  phpmyadmin:
    image: chesszebra/phpmyadmin
    environment:
      PMA_HOST: "mysqlserver"
      PMA_USER: "root"
      PMA_PASSWORD: "rootpassword"
    links:
      - mysqlserver

  webserver-apache:
    image: chesszebra/php:7.2-apache
    container_name: "oauth.lichess.org"
    volumes:
      - .:/var/www/html
    links:
      - mongoserver
      - mysqlserver
